import { test, expect } from '@playwright/test'
test('catalog is usable before 3D loads; search, compare, inquiry and persistence', async ({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('./')
  await expect(page.locator('.product-card').first()).toBeVisible()
  await expect(page.locator('canvas')).toHaveCount(0)
  expect(await page.evaluate(()=>performance.getEntriesByType('resource').some(e=>/Showroom|Walkthrough|RoundedBox/.test(e.name)))).toBe(false)
  await page.mouse.wheel(0, 600)
  await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBeGreaterThan(0)
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:'test-results/desktop.png',fullPage:true})
  const total=await page.locator('.product-card').count()
  await page.getByRole('textbox',{name:'جستجوی محصول یا تأمین‌کننده'}).fill('هیچ‌چیز‌یافت‌نشد')
  await expect(page.locator('.product-card')).toHaveCount(0)
  await page.getByRole('button',{name:'پاک کردن فیلترها'}).click()
  await expect(page.locator('.product-card')).toHaveCount(total)
  await page.getByRole('button',{name:'مقایسه',exact:true}).nth(0).click()
  await page.getByRole('button',{name:'مقایسه',exact:true}).nth(1).click()
  await page.getByRole('button',{name:'مقایسهٔ انتخاب‌ها',exact:true}).click()
  await expect(page.locator('dialog[open] table thead th')).toHaveCount(3)
  await page.keyboard.press('Escape')
  await page.locator('.add-quote').first().click()
  await page.getByRole('button',{name:/استعلام‌های من/}).click()
  await expect(page.locator('.quote-line')).toHaveCount(1)
  await page.getByRole('spinbutton').fill('12')
  await page.locator('textarea').fill('تحویل تهران')
  const download=page.waitForEvent('download')
  await page.getByRole('button',{name:/دانلود پیش‌نویس/}).click()
  expect((await download).suggestedFilename()).toBe('paper-bazaar-inquiry.txt')
  await page.reload()
  await page.getByRole('button',{name:/استعلام‌های من/}).click()
  await expect(page.getByRole('spinbutton')).toHaveValue('12')
  await expect(page.locator('textarea')).toHaveValue('تحویل تهران')
  await page.keyboard.press('Escape')
  expect(errors).toEqual([])
})
test('responsive layout and working 3D studio',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.setViewportSize({width:390,height:844})
  await page.goto('./')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/mobile.png',fullPage:true})
  await page.getByRole('button',{name:/ورود به استودیو سه‌بعدی/}).click()
  await expect(page.locator('canvas')).toBeVisible()
  await page.getByRole('button',{name:'رنگ #c18b48'}).click()
  await expect(page.getByRole('button',{name:'رنگ #c18b48'})).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button',{name:'حالت کم‌مصرف'}).click()
  await expect(page.getByRole('button',{name:'کیفیت سینمایی'})).toBeVisible()
  await page.screenshot({path:'test-results/studio.png'})
  await page.keyboard.press('Escape')
  await expect(page.locator('canvas')).toHaveCount(0)
  expect(errors).toEqual([])
})
