import { Component, lazy, Suspense, useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { seedCatalog } from '../data/catalog/seedCatalog'
import { fetchCatalog } from '../data/catalog/catalogClient'
import type { Catalog } from '../domain/catalog'
import { filterListings, listings, quoteText, restoreQuote, type Category, type Listing, type QuoteLine } from './model'
import Art from './Art'
import './market.css'
const Showroom = lazy(() => import('./Showroom'))
const Walkthrough = lazy(() => import('./Walkthrough'))
const categories: {id: Category; title: string; caption: string}[] = [{id:'all',title:'همهٔ محصولات',caption:'تمام متریال‌ها'},{id:'office',title:'کاغذ اداری',caption:'برای ایده‌های روزمره'},{id:'print',title:'چاپ و تحریر',caption:'کیفیت در هر برگ'},{id:'board',title:'مقوا و بسته‌بندی',caption:'فرم بدهید، متمایز شوید'}]
const fa = (n: number) => n.toLocaleString('fa-IR')
class SceneBoundary extends Component<{children: ReactNode},{failed:boolean}> {
  state = {failed:false}
  static getDerivedStateFromError() {return {failed:true}}
  render() {return this.state.failed ? <div className="empty">نمای سه‌بعدی در دسترس نیست. کاتالوگ و استعلام همچنان قابل استفاده‌اند.</div> : this.props.children}
}
function Dialog({title,children,onClose,wide=false,notice}: {title:string;children:ReactNode;onClose:()=>void;wide?:boolean;notice?:string}) {
  const ref=useRef<HTMLDialogElement>(null)
  useEffect(()=>{const d=ref.current; d?.showModal(); return ()=>d?.close()},[])
  return <dialog ref={ref} className={wide?'market-dialog wide':'market-dialog'} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}} dir="rtl"><div className="dialog-heading"><h2>{title}</h2><button className="icon-button" aria-label="بستن" onClick={onClose}>×</button></div>{children}{notice&&<p className="dialog-notice" role="status">✓ {notice}</p>}</dialog>
}
export default function Market() {
  const [catalog,setCatalog]=useState<Catalog>(seedCatalog)
  const items=useMemo(()=>listings(catalog),[catalog])
  const [query,setQuery]=useState(''),[category,setCategory]=useState<Category>('all'),[vendor,setVendor]=useState(''),[sort,setSort]=useState('default')
  const [onlySaved,setOnlySaved]=useState(false),[saved,setSaved]=useState<string[]>(()=>{try{const v=JSON.parse(localStorage.getItem('pb3-saved')||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'):[]}catch{return []}})
  const [quote,setQuote]=useState<QuoteLine[]>(()=>{try{return restoreQuote(JSON.parse(localStorage.getItem('pb3-quote')||'[]'),listings(seedCatalog))}catch{return []}})
  const [compare,setCompare]=useState<string[]>([]),[selected,setSelected]=useState<Listing|null>(null)
  const [panel,setPanel]=useState<'quote'|'compare'|'tour'|'studio'|null>(null),[note,setNote]=useState(()=>{try{return localStorage.getItem('pb3-note')||''}catch{return ''}}),[notice,setNotice]=useState(''),[apiStatus,setApiStatus]=useState('کاتالوگ نمونه')
  const [tourStep,setTourStep]=useState(0),[walk,setWalk]=useState(false)
  useEffect(()=>{try{localStorage.setItem('pb3-quote',JSON.stringify(quote));localStorage.setItem('pb3-saved',JSON.stringify(saved));localStorage.setItem('pb3-note',note)}catch{setNotice('ذخیره‌سازی مرورگر در دسترس نیست؛ پیش‌نویس را دانلود کنید.')}},[quote,saved,note])
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice])
  useEffect(()=>{if(import.meta.env.VITE_STATIC_DEMO==='true')return;const abort=new AbortController();fetchCatalog(abort.signal).then(c=>{setCatalog(c);setApiStatus('کاتالوگ API · قیمت‌ها اسنپ‌شات‌اند')}).catch(()=>{});return()=>abort.abort()},[])
  const visible=filterListings(items,query,category,vendor,sort).filter(p=>!onlySaved||saved.includes(p.key))
  function add(p: Listing) {setQuote(q=>q.some(l=>l.key===p.key)?q:[...q,{key:p.key,quantity:1}]);setNotice('به پیش‌نویس استعلام اضافه شد')}
  function toggleCompare(key: string) {setCompare(c=>c.includes(key)?c.filter(k=>k!==key):c.length<3?[...c,key]:c);if(compare.length===3&&!compare.includes(key))setNotice('حداکثر سه کالا را مقایسه کنید')}
  function download() {const blob=new Blob(['\ufeff'+quoteText(quote,items,note)],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='paper-bazaar-inquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function browse(c:Category='all'){setCategory(c);document.getElementById('catalog')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
  if(walk)return <div className="legacy-view"><SceneBoundary><Suspense fallback={<div className="loading">آماده‌سازی بازار سه‌بعدی…</div>}><Walkthrough quote={quote} onExit={next=>{setQuote(next);setWalk(false)}}/></Suspense></SceneBoundary></div>
  return <div className="market" dir="rtl">
    <div className="announcement"><span>نسل تازهٔ تجربهٔ خرید کاغذ</span><span>نسخهٔ نمایشی · داده‌های نمونه و عمومی</span></div>
    <header className="market-header"><a className="logo" href="#"><span className="logo-mark">▱</span><div><b>بازار کاغذ</b><small>PAPER BAZAAR / 03</small></div></a><nav aria-label="منوی اصلی"><button onClick={()=>browse()}>بازار محصولات</button><button onClick={()=>setPanel('studio')}>استودیو متریال <span className="tiny">3D</span></button><button onClick={()=>{setTourStep(0);setPanel('tour')}}>تور معرفی</button></nav><button className="quote-button" onClick={()=>setPanel('quote')}>استعلام‌های من <span>{fa(quote.length)}</span></button></header>
    <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> بازار تخصصی کاغذ، چاپ و بسته‌بندی</div><h1>ایده‌های بزرگ،<br/>از یک <em>برگ</em> شروع می‌شوند.</h1><p>متریال مناسب را کشف کنید، پیشنهاد تأمین‌کنندگان را کنار هم ببینید و با یک پیش‌نویس دقیق، گفت‌وگوی خرید را شروع کنید.</p><div className="hero-actions"><button className="primary" onClick={()=>browse()}>کشف محصولات <span>↙</span></button><button className="secondary" onClick={()=>setPanel('studio')}>ورود به استودیو سه‌بعدی ◇</button></div><div className="hero-stats"><div><b>{fa(catalog.vendors.length)}</b><span>تأمین‌کننده در کاتالوگ</span></div><div><b>{fa(items.length)}</b><span>محصول برای کشف</span></div><div><b>۳D</b><span>تجربهٔ متریال</span></div></div></div><div className="hero-visual"><div className="visual-top"><span>MATERIAL / MATTERS</span><span>COLLECTION 03</span></div><Art large/><div className="material-chip"><span className="chip-dot"/><div><b>سادگی، لمس‌پذیر می‌شود.</b><small>یک نگاه تازه به دنیای کاغذ</small></div><button aria-label="مشاهده متریال سه‌بعدی" onClick={()=>setPanel('studio')}>↗</button></div><div className="visual-bottom">PAPER. POSSIBILITIES. PEOPLE.</div></div></section>
    <section className="category-strip" aria-label="دسته‌بندی‌ها">{categories.slice(1).map((c,i)=><button key={c.id} onClick={()=>browse(c.id)}><span className={`category-icon cat-${i}`}>{['▤','◫','⬡'][i]}</span><div><b>{c.title}</b><small>{c.caption}</small></div><span>↙</span></button>)}</section>
    <section id="catalog" className="catalog-section"><div className="section-heading"><div><div className="eyebrow">CURATED MATERIALS / انتخاب متریال</div><h2>برای پروژهٔ بعدی شما.</h2></div><span className="source-status"><i/>{apiStatus}</span></div><div className="catalog-toolbar"><label className="search"><span>⌕</span><input aria-label="جستجوی محصول یا تأمین‌کننده" placeholder="نام کاغذ یا تأمین‌کننده را جست‌وجو کنید…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="پاک کردن جستجو" onClick={()=>setQuery('')}>×</button>}</label><select aria-label="تأمین‌کننده" value={vendor} onChange={e=>setVendor(e.target.value)}><option value="">همهٔ تأمین‌کنندگان</option>{catalog.vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select aria-label="مرتب‌سازی" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">ترتیب کاتالوگ</option><option value="name">نام محصول</option><option value="price">قیمت ثبت‌شده: کم به زیاد</option></select></div><div className="filter-row"><div className="tabs">{categories.map(c=><button key={c.id} aria-pressed={category===c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.title}</button>)}</div><button className={onlySaved?'saved active':'saved'} onClick={()=>setOnlySaved(!onlySaved)} aria-pressed={onlySaved}>♡ نشان‌شده‌ها</button><span className="result-count">{fa(visible.length)} محصول</span></div>{sort==='price'&&<p className="data-note">واحد و مقدار بسته‌ها متفاوت‌اند؛ ترتیب قیمت به معنی ارزان‌تر بودن هر برگ یا کیلو نیست.</p>}
    <div className="product-grid">{visible.map(p=><article className="product-card" key={p.key}><div className="product-image"><button className="art-button" aria-label={`جزئیات ${p.name}`} onClick={()=>setSelected(p)}><Art kind={p.category}/></button><button className={`favorite ${saved.includes(p.key)?'is-saved':''}`} aria-label={`نشان کردن ${p.name}`} aria-pressed={saved.includes(p.key)} onClick={()=>setSaved(s=>s.includes(p.key)?s.filter(k=>k!==p.key):[...s,p.key])}>{saved.includes(p.key)?'♥':'♡'}</button><span className="product-badge">{categories.find(c=>c.id===p.category)?.title}</span></div><div className="product-body"><span className="vendor-name">{p.vendor.name}</span><button className="product-title" onClick={()=>setSelected(p)}>{p.name}</button><div className="price"><b>{p.priceText}</b><small>اسنپ‌شات {p.observedAt}</small></div><div className="card-actions"><button className="add-quote" onClick={()=>add(p)}>{quote.some(l=>l.key===p.key)?'✓ در پیش‌نویس':'＋ افزودن به استعلام'}</button><button aria-pressed={compare.includes(p.key)} className={compare.includes(p.key)?'compare active':'compare'} onClick={()=>toggleCompare(p.key)}>مقایسه</button></div></div></article>)}</div>{!visible.length&&<div className="empty"><h3>محصولی با این فیلترها پیدا نشد.</h3><button className="secondary" onClick={()=>{setQuery('');setCategory('all');setVendor('');setOnlySaved(false)}}>پاک کردن فیلترها</button></div>}</section>
    <section className="experience-banner"><div><div className="eyebrow">BEYOND THE CATALOG</div><h2>بازار را از نزدیک تجربه کنید.</h2><p>بین غرفه‌ها قدم بزنید، نمونه‌ها را کشف کنید و داستان متریال‌ها را ببینید.</p></div><button className="light-button" onClick={()=>setWalk(true)}>گردش در بازار سه‌بعدی ↗</button></section><footer><a className="logo" href="#"><span className="logo-mark">▱</span><b>بازار کاغذ</b></a><p>{catalog.disclaimer}</p><span>PAPER BAZAAR © 2026 · CONCEPT EDITION</span></footer></main>
    {compare.length>0&&<div className="compare-bar"><span>{fa(compare.length)} کالا برای مقایسه</span><button className="primary" onClick={()=>setPanel('compare')}>مقایسهٔ انتخاب‌ها</button><button className="icon-button" aria-label="پاک کردن مقایسه" onClick={()=>setCompare([])}>×</button></div>}
    {notice&&!panel&&!selected&&<div className="toast" role="status">✓ {notice}</div>}
    {selected&&<Dialog notice={notice} title="جزئیات محصول" onClose={()=>setSelected(null)}><Art kind={selected.category}/><span className="vendor-name">{selected.vendor.name}</span><h3>{selected.name}</h3><b>{selected.priceText}</b><dl><dt>واحد در منبع</dt><dd>{selected.unit}</dd><dt>تاریخ مشاهده</dt><dd>{selected.observedAt}</dd></dl><p className="data-note">{selected.note||'قیمت و موجودی را پیش از خرید از فروشنده تأیید کنید.'}</p><div className="dialog-actions"><button className="primary" onClick={()=>add(selected)}>افزودن به استعلام</button><a className="secondary" href={selected.sourceUrl} target="_blank" rel="noreferrer">مشاهدهٔ منبع ↗</a></div><button className="text-button" onClick={()=>{setSelected(null);setPanel('studio')}}>بررسی متریال در استودیو سه‌بعدی</button></Dialog>}
    {panel==='studio'&&<Dialog notice={notice} title="استودیو متریال" wide onClose={()=>setPanel(null)}><div className="tabs">{categories.slice(1).map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.title}</button>)}</div><SceneBoundary><Suspense fallback={<div className="loading">آماده‌سازی استودیو…</div>}><Showroom kind={category==='all'?'office':category}/></Suspense></SceneBoundary></Dialog>}
    {panel==='compare'&&<Dialog notice={notice} title="مقایسهٔ انتخاب‌ها" wide onClose={()=>setPanel(null)}><p className="data-note">این محصولات لزوماً هم‌ارز نیستند. برای مقایسهٔ قیمت، گرماژ، ابعاد و واحد فروش را تأیید کنید.</p><div className="comparison-scroll"><table><thead><tr><th>مشخصه</th>{items.filter(p=>compare.includes(p.key)).map(p=><th key={p.key}>{p.name}</th>)}</tr></thead><tbody>{['تأمین‌کننده','قیمت ثبت‌شده','واحد فروش','تاریخ مشاهده','استعلام'].map((label,i)=><tr key={label}><th>{label}</th>{items.filter(p=>compare.includes(p.key)).map(p=><td key={p.key}>{i===0?p.vendor.name:i===1?p.priceText:i===2?p.unit:i===3?p.observedAt:<button className="secondary" onClick={()=>add(p)}>افزودن</button>}</td>)}</tr>)}</tbody></table></div></Dialog>}
    {panel==='quote'&&<Dialog notice={notice} title="پیش‌نویس استعلام شما" wide onClose={()=>setPanel(null)}><p className="data-note">این درخواست هنوز ارسال نشده است. واحد فروش و قیمت نهایی باید توسط تأمین‌کننده تأیید شوند.</p>{quote.length? <>{quote.map(line=>{const p=items.find(p=>p.key===line.key);return p&&<div className="quote-line" key={line.key}><div><small>{p.vendor.name}</small><b>{p.name}</b><span>{p.priceText}</span></div><label>تعداد درخواستی<input aria-label={`تعداد ${p.name}`} type="number" min="1" max="9999" value={line.quantity} onChange={e=>{const n=Number(e.target.value);setQuote(q=>q.map(l=>l.key===line.key?{...l,quantity:Math.max(1,Math.min(9999,Math.floor(n)||1))}:l))}}/></label><button className="icon-button" aria-label={`حذف ${p.name}`} onClick={()=>setQuote(q=>q.filter(l=>l.key!==line.key))}>×</button></div>})}<label className="note-label">توضیحات سفارش<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="شهر تحویل، گرماژ، ابعاد و زمان موردنیاز…"/></label><div className="dialog-actions"><button className="primary" onClick={download}>دانلود پیش‌نویس استعلام ↓</button><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(quoteText(quote,items,note));setNotice('متن استعلام کپی شد')}catch{setNotice('امکان کپی نیست؛ فایل را دانلود کنید')}}}>کپی متن</button></div></>:<div className="empty"><h3>هنوز کالایی انتخاب نکرده‌اید.</h3><button className="primary" onClick={()=>{setPanel(null);browse()}}>کشف محصولات</button></div>}</Dialog>}
    {panel==='tour'&&<Dialog notice={notice} title="یک مسیر کوتاه، از کشف تا گفت‌وگو" onClose={()=>setPanel(null)}><div className="tour-number">0{tourStep+1} / 03</div><h3>{['کشف متریال مناسب','تصمیم‌گیری با اطلاعات روشن','آماده برای گفت‌وگو با فروشنده'][tourStep]}</h3><p>{['با جستجوی فارسی، دسته‌بندی و انتخاب تأمین‌کننده به محصول برسید. نشان‌شده‌ها برای بازدید بعدی در مرورگر باقی می‌مانند.','تا سه محصول را کنار هم ببینید؛ منبع، تاریخ و واحد فروش در دسترس است. استودیو سه‌بعدی، جنس و فرم را به‌صورت مفهومی نمایش می‌دهد.','کالاها، تعداد و شرایط تحویل را در یک پیش‌نویس جمع کنید و فایل را دانلود کنید. این دمو پرداخت یا ارسال واقعی سفارش ندارد.'][tourStep]}</p><button className="primary" onClick={()=>tourStep<2?setTourStep(t=>t+1):(setPanel(null),browse())}>{tourStep<2?'مرحلهٔ بعد ←':'شروع کشف محصولات'}</button></Dialog>}
  </div>
}
